name: marketviewer
services:
  marketviewer-api:
    container_name: marketviewer-backend
    image: ${IMAGE}
    ports:
      - '7158:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    env_file:
      - ../${ENVIRONMENT}.env