name: marketviewer
services:
  marketviewer-api:
    container_name: marketviewer-backend
    build:
      context: ./src
      dockerfile: MarketViewer.Api.Dockerfile
    ports:
      - '7158:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    env_file:
      - ../../docker.env
    networks:
      - marketviewer
  
  marketviewer-web:
    container_name: marketviewer-frontend
    build:
      context: ./src
      dockerfile: MarketViewer.Web.Dockerfile
    depends_on:
      - marketviewer-api
    ports:
      - '7025:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - marketviewer

networks:
  marketviewer:
    name: marketviewer
    driver: bridge
