name: marketviewer
services:
  marketviewer-api:
    build:
      context: ./src
      dockerfile: MarketViewer.Api.Dockerfile
    ports:
      - '8000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    env_file:
      - ./src/MarketViewer.Api/dev.env
    networks:
      - marketviewer
  
  marketviewer-web:
    build:
      context: ./src
      dockerfile: MarketViewer.Web.Dockerfile
      args:
        - Environment=dev
    depends_on:
      - marketviewer-api
    ports:
      - '8100:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    networks:
      - marketviewer

networks:
  marketviewer:
    name: marketviewer
