name: Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev

jobs:
  deploy:
    uses: rwitzlib/github-action-templates/.github/workflows/container-deployment.yml@MARK-165-fix-docker-datetime
    with:
      environment: ${{ inputs.environment || 'dev'}}
      docker: |
        [
          {
            "name": "api",
            "ecr_repo": "lad-${{ inputs.environment || 'dev'}}-marketviewer-api",
            "dockerfile": "./src/MarketViewer.Api.Dockerfile",
            "context": "./src",
          },
          {
            "name": "web",
            "ecr_repo": "lad-${{ inputs.environment || 'dev'}}-marketviewer-web",
            "dockerfile": "./src/MarketViewer.Web.Dockerfile",
            "context": "./src",
          }
        ]
      solution_directory: ./src
      global_json_file: "./src/global.json"
      terraform_directory: ./tf
    secrets: inherit
    