name: Nuget Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Dotnet Build
        uses: rwitzlib/github-action-templates/.github/actions/dotnet-build@v1.0.0
        with:
          project_directory: ./src
          global_json_file: ./src/global.json

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        project: [./src/MarketViewer.Contracts, ./src/MarketViewer.Studies']
    steps:
      - name: Publish Nuget Packages
        uses: rwitzlib/github-action-templates/.github/actions/nuget-publish@v1.0.0
        with:
          project_name: ${{ matrix.project }}
          global_json_file: ./src/global.json
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    